services:
  minio:
    image: minio/minio:latest
    container_name: careflow-minio
    restart: unless-stopped
    ports:
      - "9200:9000"  # Using 9200 (outside Windows reserved range 8950-9149)
      - "9201:9001"  # Console on 9201
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - careflow_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: careflow_app
    restart: unless-stopped
    ports:
      - "5001:8000"
    env_file:
      - .env
    environment:
      # Keep this as minio:9000 - it's the internal container port
      S3_ENDPOINT: http://minio:9000
      S3_KEY: minioadmin
      S3_SECRET: minioadmin
      S3_BUCKET: careflow-bucket
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - careflow_network
    command: ["sh", "-c", "sleep 5 && npm run dev"]
    depends_on:
      - minio

volumes:
  minio_data:

networks:
  careflow_network:
    driver: bridge