version: "3.8"
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      # pour que le conteneur serveur accède à minio par service name
      S3_ENDPOINT: http://minio:9000
      S3_KEY: minioadmin
      S3_SECRET: minioadmin
      S3_BUCKET: careflow-bucket
    ports:
      - "8000:8000"
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    restart: unless-stopped
